"""authy support

Revision ID: 99a83088f91c
Revises: 834b1a697901
Create Date: 2019-12-03 11:57:21.447277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99a83088f91c'
down_revision = '834b1a697901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('authy_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_authy_id'), 'user', ['authy_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_authy_id'), table_name='user')
    op.drop_column('user', 'authy_id')
    # ### end Alembic commands ###
